version: "3.4"
services:
    spickup_web_prod:
        build: .
        container_name: spickup_prod
        ports:
            - "8084:80"
        depends_on:
            - spickup_database
    spickup_web_test:
        build: .
        container_name: spickup_test
        ports:
            - "8086:80"
        depends_on:
            - spickup_database
    spickup_database:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: spickup_mssql_server
        environment:
            SA_PASSWORD: "wapwap@564"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
        ports:
            - "1433:1433"
        volumes:
            - C:\SpickupSQLServer:/var/opt/mssql/data    
volumes:
  spickup_data:  